### ISSUE TITLE
AttributeError: partially initialized module

### ISSUE THREAD

**Issue by GregoryEAllen** [codingjoe/ssdp#11]
I'm trying to run the example and I can't even import the module without an error.

I'm running in a miniconda environment on macOS.

```console
$ python --version
Python 3.8.2

$ pip install --force-reinstall ssdp
Processing /Users/gallen/Library/Caches/pip/wheels/73/4e/68/2ec3cc37f7ca10dad4f66efedca2d84b5fb704af351b46b8a9/ssdp-1.0.1-py3-none-any.whl
Installing collected packages: ssdp
  Attempting uninstall: ssdp
    Found existing installation: ssdp 1.0.1
    Uninstalling ssdp-1.0.1:
      Successfully uninstalled ssdp-1.0.1
Successfully installed ssdp-1.0.1

$ python -m ssdp
Traceback (most recent call last):
  File "/Users/gallen/miniconda3/envs/default/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/gallen/miniconda3/envs/default/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/gallen/Desktop/ssdp.py", line 2, in <module>
    import ssdp
  File "/Users/gallen/Desktop/ssdp.py", line 4, in <module>
    class MyProtocol(ssdp.SimpleServiceDiscoveryProtocol):
AttributeError: partially initialized module 'ssdp' has no attribute 'SimpleServiceDiscoveryProtocol' (most likely due to a circular import)

$ python
Python 3.8.2 (default, Mar 26 2020, 10:43:30) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import asyncio
>>> import socket
>>> import ssdp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gallen/Desktop/ssdp.py", line 4, in <module>
    class MyProtocol(ssdp.SimpleServiceDiscoveryProtocol):
AttributeError: partially initialized module 'ssdp' has no attribute 'SimpleServiceDiscoveryProtocol' (most likely due to a circular import)
```

Any ideas or suggestions?

**Comment by GregoryEAllen** [comment]
PEBKAC. See https://github.com/jstasiak/python-zeroconf/issues/90
