### ISSUE TITLE
MSearch example WinError 10022 on Windows and shows nothing

### ISSUE THREAD

**Issue by alessandromannini** [codingjoe/ssdp#84]
Hi,

i tried the MSearch example on Windows. Nothing is discovered on the network but I get this error:
`Exception in callback _ProactorDatagramTransport._loop_reading()`
`handle: <Handle _ProactorDatagramTransport._loop_reading()>`
`Traceback (most recent call last):`
`  File "C:\Python39\lib\asyncio\proactor_events.py", line 566, in _loop_reading`
`    self._read_fut = self._loop._proactor.recvfrom(self._sock,`
`  File "C:\Python39\lib\asyncio\windows_events.py", line 494, in recvfrom`
`    ov.WSARecvFrom(conn.fileno(), nbytes, flags)`
`OSError: [WinError 10022] Argomento fornito non valido`
``
`The above exception was the direct cause of the following exception:`
``
`Traceback (most recent call last):`
`  File "C:\Python39\lib\asyncio\events.py", line 80, in _run`
`    self._context.run(self._callback, *self._args)`
`  File "C:\Python39\lib\asyncio\proactor_events.py", line 569, in _loop_reading`
`    self._protocol.error_received(exc)`
`  File "C:\Python39\lib\site-packages\ssdp\__init__.py", line 177, in error_received`
`    raise IOError("Unexpected connection error") from exc`
`OSError: Unexpected connection error`

The message "Argomento fornito non valido" is "Invalid argument" in English :).
Can you help me?

Thx
Alessandro

**Comment by alessandromannini** [comment]
Duplicate of https://github.com/codingjoe/ssdp/issues/71
